insert into stations (station_name, station_address) values ('605 Muir Street', '10248 Northfield Lane');
insert into stations (station_name, station_address) values ('9566 Bellgrove Trail', '20922 Banding Pass');
insert into stations (station_name, station_address) values ('7488 Mayer Plaza', '8187 Colorado Trail');
insert into stations (station_name, station_address) values ('04863 Loftsgordon Road', '80 Dahle Pass');
insert into stations (station_name, station_address) values ('8173 School Way', '3875 Lake View Pass');
insert into stations (station_name, station_address) values ('22280 Pepper Wood Lane', '10 Arkansas Pass');
insert into stations (station_name, station_address) values ('04 Reinke Street', '3 Porter Street');
insert into stations (station_name, station_address) values ('7223 Hayes Road', '86 Pond Avenue');
insert into stations (station_name, station_address) values ('497 Becker Crossing', '83589 Gulseth Court');
insert into stations (station_name, station_address) values ('56903 School Lane', '1 Corry Terrace');
insert into stations (station_name, station_address) values ('11645 Main Pass', '268 Debra Junction');
insert into stations (station_name, station_address) values ('9124 Sullivan Place', '5 Summer Ridge Parkway');
insert into stations (station_name, station_address) values ('0 Cherokee Pass', '71 Melrose Place');
insert into stations (station_name, station_address) values ('2406 Oak Valley Alley', '80715 Kingsford Center');
insert into stations (station_name, station_address) values ('42 School Alley', '164 Village Plaza');
insert into stations (station_name, station_address) values ('3 Schiller Circle', '5538 Washington Street');
insert into stations (station_name, station_address) values ('0908 Buell Pass', '4 Walton Pass');
insert into stations (station_name, station_address) values ('4518 Manley Alley', '857 Killdeer Junction');
insert into stations (station_name, station_address) values ('0 6th Drive', '6 Declaration Road');
insert into stations (station_name, station_address) values ('120 Porter Circle', '82 Mockingbird Crossing');
insert into stations (station_name, station_address) values ('5 Brentwood Trail', '206 Namekagon Lane');
insert into stations (station_name, station_address) values ('0984 Burrows Avenue', '44 Doe Crossing Terrace');
insert into stations (station_name, station_address) values ('82 Melvin Junction', '9 Tennyson Pass');
insert into stations (station_name, station_address) values ('4 Lunder Drive', '1 Bayside Lane');
insert into stations (station_name, station_address) values ('264 Dunning Crossing', '4 Bartelt Trail');
insert into stations (station_name, station_address) values ('25294 8th Court', '96753 Anhalt Lane');
insert into stations (station_name, station_address) values ('8186 Portage Place', '77 Elka Trail');
insert into stations (station_name, station_address) values ('2136 Warrior Road', '7 Eastlawn Trail');
insert into stations (station_name, station_address) values ('8 Golf Parkway', '679 Lakewood Pass');
insert into stations (station_name, station_address) values ('10662 John Wall Center', '60766 Shelley Plaza');
insert into stations (station_name, station_address) values ('55706 Mitchell Junction', '234 Becker Court');
insert into stations (station_name, station_address) values ('152 Pine View Court', '40105 Mockingbird Lane');
insert into stations (station_name, station_address) values ('050 Starling Plaza', '79 Buell Crossing');
insert into stations (station_name, station_address) values ('6 Springview Park', '1301 Swallow Lane');
insert into stations (station_name, station_address) values ('5 Claremont Lane', '8 Melrose Street');
insert into stations (station_name, station_address) values ('04353 Sage Road', '27321 Dakota Way');
insert into stations (station_name, station_address) values ('3141 Northview Plaza', '6 Stephen Avenue');
insert into stations (station_name, station_address) values ('8 Hoepker Center', '654 Welch Park');
insert into stations (station_name, station_address) values ('9457 Tennessee Street', '808 Roth Hill');
insert into stations (station_name, station_address) values ('4 Monterey Crossing', '80583 Comanche Street');
insert into stations (station_name, station_address) values ('3 Meadow Vale Hill', '71662 Sachtjen Circle');
insert into stations (station_name, station_address) values ('7143 Delaware Trail', '0634 Melby Drive');
insert into stations (station_name, station_address) values ('541 Shoshone Hill', '25 School Trail');
insert into stations (station_name, station_address) values ('0 Sutteridge Trail', '3 Twin Pines Drive');
insert into stations (station_name, station_address) values ('70 Portage Street', '378 Rieder Trail');
insert into stations (station_name, station_address) values ('638 Basil Trail', '1 Delladonna Terrace');
insert into stations (station_name, station_address) values ('39 Glacier Hill Center', '843 Logan Trail');
insert into stations (station_name, station_address) values ('9355 Merrick Alley', '91 Carpenter Terrace');
insert into stations (station_name, station_address) values ('31154 Forest Trail', '15303 Hermina Court');
insert into stations (station_name, station_address) values ('51494 Hovde Street', '6621 Westend Pass');
insert into stations (station_name, station_address) values ('22593 Melody Pass', '9177 Ilene Park');
insert into stations (station_name, station_address) values ('9 Hallows Pass', '758 Redwing Court');
insert into stations (station_name, station_address) values ('08962 Sunfield Road', '8944 Esch Trail');
insert into stations (station_name, station_address) values ('65 Jenifer Crossing', '26 Leroy Crossing');
insert into stations (station_name, station_address) values ('303 Fair Oaks Crossing', '8522 Elmside Place');
insert into stations (station_name, station_address) values ('397 Nova Lane', '166 Loeprich Pass');
insert into stations (station_name, station_address) values ('99 Rockefeller Park', '32245 Dorton Way');
insert into stations (station_name, station_address) values ('23623 Old Gate Park', '8 Calypso Plaza');
insert into stations (station_name, station_address) values ('7 Jenifer Circle', '3209 Moulton Pass');
insert into stations (station_name, station_address) values ('7202 Thompson Pass', '0604 Hermina Alley');
insert into stations (station_name, station_address) values ('55 Reindahl Plaza', '841 Northfield Crossing');
insert into stations (station_name, station_address) values ('13 Holy Cross Terrace', '80515 Main Lane');
insert into stations (station_name, station_address) values ('8983 Ludington Court', '8 Di Loreto Pass');
insert into stations (station_name, station_address) values ('099 Towne Park', '69300 6th Road');
insert into stations (station_name, station_address) values ('6389 Burning Wood Place', '1 Eagle Crest Way');
insert into stations (station_name, station_address) values ('7 Dryden Place', '53153 Merry Road');
insert into stations (station_name, station_address) values ('535 Huxley Crossing', '7937 Eastwood Parkway');
insert into stations (station_name, station_address) values ('1418 Jenna Park', '7997 Gulseth Alley');
insert into stations (station_name, station_address) values ('32983 Northland Trail', '82 Main Court');
insert into stations (station_name, station_address) values ('7 Lyons Drive', '3 Havey Crossing');
insert into stations (station_name, station_address) values ('9 Everett Road', '2 Westridge Crossing');
insert into stations (station_name, station_address) values ('46 Cottonwood Point', '5 Kingsford Court');
insert into stations (station_name, station_address) values ('91064 Huxley Alley', '57880 Scofield Parkway');
insert into stations (station_name, station_address) values ('6595 Kensington Pass', '1 John Wall Place');
insert into stations (station_name, station_address) values ('9 Kings Crossing', '7 Acker Junction');
insert into stations (station_name, station_address) values ('138 Sloan Avenue', '8692 Atwood Circle');
insert into stations (station_name, station_address) values ('5 Sugar Street', '60266 Helena Point');
insert into stations (station_name, station_address) values ('178 Rieder Street', '81155 Rigney Center');
insert into stations (station_name, station_address) values ('712 International Way', '057 Oak Valley Alley');
insert into stations (station_name, station_address) values ('19511 Dahle Park', '95359 Nancy Trail');
insert into stations (station_name, station_address) values ('37 Gateway Point', '64 Blue Bill Park Plaza');
insert into stations (station_name, station_address) values ('99 Londonderry Junction', '6336 Lyons Parkway');
insert into stations (station_name, station_address) values ('046 Pierstorff Crossing', '94412 5th Parkway');
insert into stations (station_name, station_address) values ('29052 Stone Corner Trail', '8 Eagan Avenue');
insert into stations (station_name, station_address) values ('0081 Judy Crossing', '181 Drewry Pass');
insert into stations (station_name, station_address) values ('4 Myrtle Center', '7 Mallory Court');
insert into stations (station_name, station_address) values ('7 Bonner Road', '4 Spohn Trail');
insert into stations (station_name, station_address) values ('1735 Northridge Terrace', '6935 Dunning Terrace');
insert into stations (station_name, station_address) values ('5840 Clemons Center', '972 Rusk Circle');
insert into stations (station_name, station_address) values ('53820 Dennis Way', '0666 Everett Junction');
insert into stations (station_name, station_address) values ('14 Milwaukee Court', '63746 Mayfield Street');
insert into stations (station_name, station_address) values ('469 Superior Road', '864 Ruskin Park');
insert into stations (station_name, station_address) values ('34 Grim Way', '84152 Thierer Place');
insert into stations (station_name, station_address) values ('5 Eastlawn Crossing', '45 Jana Trail');
insert into stations (station_name, station_address) values ('25257 6th Parkway', '2531 Farragut Junction');
insert into stations (station_name, station_address) values ('364 Park Meadow Trail', '0389 Vidon Point');
insert into stations (station_name, station_address) values ('67784 Melody Way', '8516 Spohn Drive');
insert into stations (station_name, station_address) values ('868 Bartillon Drive', '873 Caliangt Place');
insert into stations (station_name, station_address) values ('47108 Memorial Lane', '0 Meadow Valley Crossing');
insert into stations (station_name, station_address) values ('0592 Myrtle Parkway', '9 Morning Terrace');
