insert into trains (model, capacity) values ('Elantra', 1);
insert into trains (model, capacity) values ('3500 Club Coupe', 2);
insert into trains (model, capacity) values ('Envoy XL', 3);
insert into trains (model, capacity) values ('Matrix', 4);
insert into trains (model, capacity) values ('Ram Wagon B250', 5);
insert into trains (model, capacity) values ('Mazdaspeed6', 6);
insert into trains (model, capacity) values ('QX', 7);
insert into trains (model, capacity) values ('3 Series', 8);
insert into trains (model, capacity) values ('Suburban 1500', 9);
insert into trains (model, capacity) values ('J', 10);
insert into trains (model, capacity) values ('Town & Country', 11);
insert into trains (model, capacity) values ('Expo', 12);
insert into trains (model, capacity) values ('Tracer', 13);
insert into trains (model, capacity) values ('LTD Crown Victoria', 14);
insert into trains (model, capacity) values ('Mark VII', 15);
insert into trains (model, capacity) values ('Suburban 1500', 16);
insert into trains (model, capacity) values ('Astro', 17);
insert into trains (model, capacity) values ('CTS-V', 18);
insert into trains (model, capacity) values ('Dakota Club', 19);
insert into trains (model, capacity) values ('3500', 20);
insert into trains (model, capacity) values ('Grand Prix', 21);
insert into trains (model, capacity) values ('Grand Vitara', 22);
insert into trains (model, capacity) values ('Escort', 23);
insert into trains (model, capacity) values ('9-3', 24);
insert into trains (model, capacity) values ('Stratus', 25);
insert into trains (model, capacity) values ('599 GTB Fiorano', 26);
insert into trains (model, capacity) values ('Avalanche', 27);
insert into trains (model, capacity) values ('LTD Crown Victoria', 28);
insert into trains (model, capacity) values ('Quattro', 29);
insert into trains (model, capacity) values ('X5', 30);
insert into trains (model, capacity) values ('SC', 31);
insert into trains (model, capacity) values ('Elise', 32);
insert into trains (model, capacity) values ('Verona', 33);
insert into trains (model, capacity) values ('Crown Victoria', 34);
insert into trains (model, capacity) values ('Sienna', 35);
insert into trains (model, capacity) values ('626', 36);
insert into trains (model, capacity) values ('SLS-Class', 37);
insert into trains (model, capacity) values ('Monterey', 38);
insert into trains (model, capacity) values ('Sorento', 39);
insert into trains (model, capacity) values ('Riviera', 40);
insert into trains (model, capacity) values ('Swift', 41);
insert into trains (model, capacity) values ('Sentra', 42);
insert into trains (model, capacity) values ('240SX', 43);
insert into trains (model, capacity) values ('E-Class', 44);
insert into trains (model, capacity) values ('HS', 45);
insert into trains (model, capacity) values ('NSX', 46);
insert into trains (model, capacity) values ('Neon', 47);
insert into trains (model, capacity) values ('Cabriolet', 48);
insert into trains (model, capacity) values ('Q', 49);
insert into trains (model, capacity) values ('Galant', 50);
insert into trains (model, capacity) values ('X-Type', 51);
insert into trains (model, capacity) values ('A3', 52);
insert into trains (model, capacity) values ('Ram Wagon B350', 53);
insert into trains (model, capacity) values ('VUE', 54);
insert into trains (model, capacity) values ('SVX', 55);
insert into trains (model, capacity) values ('Sephia', 56);
insert into trains (model, capacity) values ('Viper RT/10', 57);
insert into trains (model, capacity) values ('LTD', 58);
insert into trains (model, capacity) values ('Grand Marquis', 59);
insert into trains (model, capacity) values ('Century', 60);
insert into trains (model, capacity) values ('V70', 61);
insert into trains (model, capacity) values ('Continental', 62);
insert into trains (model, capacity) values ('Coachbuilder', 63);
insert into trains (model, capacity) values ('Accent', 64);
insert into trains (model, capacity) values ('Windstar', 65);
insert into trains (model, capacity) values ('tC', 66);
insert into trains (model, capacity) values ('Summit', 67);
insert into trains (model, capacity) values ('RX-7', 68);
insert into trains (model, capacity) values ('Tracer', 69);
insert into trains (model, capacity) values ('Silverado 1500', 70);
insert into trains (model, capacity) values ('STS', 71);
insert into trains (model, capacity) values ('Escape', 72);
insert into trains (model, capacity) values ('Quest', 73);
insert into trains (model, capacity) values ('Gallardo', 74);
insert into trains (model, capacity) values ('Daytona', 75);
insert into trains (model, capacity) values ('Swift', 76);
insert into trains (model, capacity) values ('Edge', 77);
insert into trains (model, capacity) values ('Lightning', 78);
insert into trains (model, capacity) values ('Stealth', 79);
insert into trains (model, capacity) values ('G', 80);
insert into trains (model, capacity) values ('M', 81);
insert into trains (model, capacity) values ('XK', 82);
insert into trains (model, capacity) values ('Optima', 83);
insert into trains (model, capacity) values ('Park Avenue', 84);
insert into trains (model, capacity) values ('Bonneville', 85);
insert into trains (model, capacity) values ('CT', 86);
insert into trains (model, capacity) values ('Yukon XL 1500', 87);
insert into trains (model, capacity) values ('Kizashi', 88);
insert into trains (model, capacity) values ('Swift', 89);
insert into trains (model, capacity) values ('Brat', 90);
insert into trains (model, capacity) values ('Discovery', 91);
insert into trains (model, capacity) values ('Fiero', 92);
insert into trains (model, capacity) values ('GTO', 93);
insert into trains (model, capacity) values ('Electra', 94);
insert into trains (model, capacity) values ('Lancer', 95);
insert into trains (model, capacity) values ('Excel', 96);
insert into trains (model, capacity) values ('S10', 97);
insert into trains (model, capacity) values ('Avalon', 98);
insert into trains (model, capacity) values ('Clubman', 99);
insert into trains (model, capacity) values ('Continental Mark VII', 100);
